### ISSUE TITLE
Benchmark inaccurate

### ISSUE THREAD

**Issue by niftylettuce** [codeandcats/fast-clone#27]
To run the benchmarks I had to lock `jsdom` to `npm install -D jsdom@11.12.0` because `benv` doesn't specify a version range, and the new `jsdom` has deprecated methods that were being used by `benv`.

Anyways, the benchmarks consistently showed `rfdc` as the fastest approach.

```sh
λ ~/Projects/fast-clone/ master* npm run benchmark

> fast-clone@1.5.13 benchmark /Users/jack/Projects/fast-clone
> ts-node --files ./support/benchmark

Generating random json data...
Done.

Test data size is:  7.15 MB

Running benchmark 1 of 7... Done
Running benchmark 2 of 7... Done
Running benchmark 3 of 7... Done
Running benchmark 4 of 7... Done
Running benchmark 5 of 7... Done
Running benchmark 6 of 7... Done
Running benchmark 7 of 7... Done

Library          | Time
-----------------|---------
clone            | 2,181 ms
angular.copy     | 1,715 ms
snapshot         | 1,182 ms
lodash.cloneDeep |   197 ms
fast-clone       |   149 ms
deepClone        |   139 ms
rfdc             |    35 ms
```

**Comment by niftylettuce** [comment]
```sh
node --version
v10.15.3
```

**Comment by niftylettuce** [comment]
Note I added <https://github.com/davidmarkclements/rfdc> to the benchmark.

**Comment by niftylettuce** [comment]
Note that `rfdc` benchmark had the following result, which placed this package last:

```sh
λ ~/Projects/rfdc/ master* npm run bench

> rfdc@1.1.4 bench /Users/jack/Projects/rfdc
> node benchmark

benchDeepCopy*100: 748.877ms
benchLodashCloneDeep*100: 1893.592ms
benchFastClone*100: 3946.849ms  <------------
benchFastCopy*100: 1056.753ms
benchRfdc*100: 427.176ms
benchRfdcProto*100: 435.255ms
benchRfdcCircles*100: 490.022ms
benchRfdcCirclesProto*100: 487.759ms
benchDeepCopy*100: 750.964ms
benchLodashCloneDeep*100: 1955.513ms
benchFastClone*100: 4271.341ms  <------------
benchFastCopy*100: 1088.407ms
benchRfdc*100: 528.183ms
benchRfdcProto*100: 529.741ms
benchRfdcCircles*100: 497.151ms
benchRfdcCirclesProto*100: 486.490ms
```

`fast-clone` ran in `3946ms` vs `rfdc` which ran in `427ms`

According to those benchmarks this package is 9x as slow.  Just wanted to make sure you were aware.

**Comment by niftylettuce** [comment]
I updated my test result above with accurate output, `fast-clone` is 3rd with 149ms, `deepClone` 2nd with 139ms, and `rfdc` 1st with 35ms.  https://github.com/codeandcats/fast-clone/issues/27#issue-454866524

**Comment by codeandcats** [comment]
Thanks for that nifty.

This library was the fastest I could find on npm at one point in time but over the years other libraries have caught up and even surpassed it in speed.

I recently had a go at completely rewriting it in order to improve performance and add some features at the same time, but it was a trade off between features and perf and I wasn't prepared to sacrifice functionality.

I've been thinking that I'll probably just deprecate the library.

**Comment by niftylettuce** [comment]
You could put in your deprecation notice to use rfdc, and then publish a new version `1.5.14` that uses `rfdc` internally or something.  I'm sure GitHub support could help setup a redirect from fast-clone to rfdc.

**Comment by niftylettuce** [comment]
You could also use the "ARCHIVE" feature of GitHub and put up a deprecation notice in README and via `npm deprecate`
